// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5TWEIFGa1KzDvy-_rXc-ohPQjQbJAEjE',
    appId: '1:661450530152:web:01ad0a8bde512355d74add',
    messagingSenderId: '661450530152',
    projectId: 'yemekhane-app-adi',
    authDomain: 'yemekhane-app-adi.firebaseapp.com',
    storageBucket: 'yemekhane-app-adi.firebasestorage.app',
    measurementId: 'G-7NY0KNLGPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATa-ONgtdyg-unRYDL8igso8b6ZU1M_9g',
    appId: '1:661450530152:android:ec6e4056af47686dd74add',
    messagingSenderId: '661450530152',
    projectId: 'yemekhane-app-adi',
    storageBucket: 'yemekhane-app-adi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj59Xwyg-ITqx6dQnRTJsn2EMGnByHeUc',
    appId: '1:661450530152:ios:5184a4618847b482d74add',
    messagingSenderId: '661450530152',
    projectId: 'yemekhane-app-adi',
    storageBucket: 'yemekhane-app-adi.firebasestorage.app',
    iosBundleId: 'com.karfagen.manasYemek',
  );
}
