// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ManasYemek/features/menu/domain/entities/daily_menu_entity.dart';
import 'package:ManasYemek/features/menu/domain/entities/menu_item_entity.dart';
//import 'package:ManasYemek/models/daily_menu.dart';
//import 'package:ManasYemek/models/menu_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    //registerAdapter(DailyMenuAdapter());
    registerAdapter(DailyMenuEntityAdapter());
    //registerAdapter(MenuItemAdapter());
    registerAdapter(MenuItemEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    //registerAdapter(DailyMenuAdapter());
    registerAdapter(DailyMenuEntityAdapter());
    //registerAdapter(MenuItemAdapter());
    registerAdapter(MenuItemEntityAdapter());
  }
}
