// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ManasYemek/features/menu/data/models/local/daily_menu_model.dart';
import 'package:ManasYemek/features/menu/data/models/local/menu_item_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DailyMenuModelAdapter());
    registerAdapter(MenuItemModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DailyMenuModelAdapter());
    registerAdapter(MenuItemModelAdapter());
  }
}
